Repository wecode-bootcamp-korea/24-2nd-FLIP-backend, pull requests merged in 2021-09, with the labels that each got.

#1 [24기 성우진] 초기 모델링
  carts/__init__.py
  carts/admin.py
  carts/apps.py
  carts/migrations/0001_initial.py
  carts/migrations/__init__.py
  carts/models.py
  carts/tests.py
  carts/views.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  flip/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_auto_20210915_1512.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210915_1512.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210915_1512.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#5 Edited: emergency change in modeling
  users/models.py
Labels: Status: 리뷰 요청

#8 [24기 성우진] 모델링 변경
  products/models.py
Labels: Status: 리뷰 요청

#14 [24기 성우진] 모델링 변경
  products/models.py
  users/models.py
Labels: Status: 리뷰 요청

#15 [서동규]ADD: S3bucket settings
  core/storages.py
  flip/settings.py
  flip/urls.py
  products/views.py
  requirements.txt
Labels: Status: Accepted

#11 [24기 성우진] ListCategoryView
  carts/migrations/0002_auto_20210916_2008.py
  flip/urls.py
  orders/migrations/0003_auto_20210916_2008.py
  products/migrations/0004_auto_20210916_2008.py
  products/tests.py
  products/urls.py
  products/views.py
  users/migrations/0004_auto_20210916_2008.py
Labels: Status: Accepted

#13 [서동규]ADD: DetailView
  .gitignore
  core/storages.py
  flip/settings.py
  flip/urls.py
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#16 [손명희] Add:Kakao_signin
  carts/migrations/0002_auto_20210916_2024.py
  flip/settings.py
  flip/urls.py
  orders/migrations/0003_auto_20210916_2024.py
  products/migrations/0004_auto_20210916_2024.py
  requirements.txt
  users/migrations/0004_auto_20210916_2025.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#17 [서동규]ADD: LikeView
  products/tests.py
  products/urls.py
  products/views.py
  users/decorator.py
Labels: Status: 리뷰 요청

#18 [서동규]ADD:ReviewView
  products/tests.py
  products/urls.py
  products/views.py
  users/migrations/0004_auto_20210916_2008.py
Labels: Status: 리뷰 요청

#19 [손명희]Add:UserProductView
  flip/settings.py
  products/migrations/0005_alter_maincategory_image_url.py
  products/tests.py
  products/urls.py
  products/views.py
  users/migrations/0005_alter_bankaccount_account_number.py
Labels: Status: 리뷰 요청

#21 [24기 성우진] Main Page Category View
  flip/settings.py
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#24 [서동규] 긴급!!! 모델링 수정
  carts/migrations/0001_initial.py
  carts/migrations/0002_auto_20210916_2008.py
  carts/migrations/0002_auto_20210916_2024.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_auto_20210915_1512.py
  orders/migrations/0003_auto_20210916_2008.py
  orders/migrations/0003_auto_20210916_2024.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210915_1512.py
  products/migrations/0003_auto_20210916_1132.py
  products/migrations/0004_auto_20210916_2008.py
  products/migrations/0004_auto_20210916_2024.py
  products/migrations/0005_alter_maincategory_image_url.py
  products/models.py
  products/tests.py
  products/views.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210915_1512.py
  users/migrations/0003_alter_user_email.py
  users/migrations/0004_auto_20210916_2008.py
  users/migrations/0004_auto_20210916_2025.py
  users/migrations/0005_alter_bankaccount_account_number.py
Labels: Merge 요청

#25 [손명희]긴급!!!!! Add:user_product_get_unittest
  carts/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/tests.py
  products/views.py
  requirements.txt
  users/migrations/0001_initial.py
  users/tests.py
  users/views.py
Labels: Merge 요청

#20 [손명희]Add:BankAccountView
  carts/migrations/0001_initial.py
  flip/urls.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/views.py
  users/migrations/0001_initial.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 수정 요청

#26 [손명희] 긴급!! Add:kakao_signin
  carts/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/views.py
  users/migrations/0001_initial.py
  users/tests.py
  users/views.py
Labels: Merge 요청

#28 긴급!![손명희]Add:Kakao_signin (login_decorator 위치 변경)
  Flip.sql
  carts/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  users/migrations/0001_initial.py
  users/views.py
Labels: Merge 요청

#27 [24기 성우진] Added: Product List View
  flip/settings.py
  products/tests.py
  products/urls.py
  products/views.py
  users/tests.py
Labels: Status: 리뷰 요청

#29 [서동규] 진짜 긴급!!! ADD:Location View
  products/tests.py
  products/urls.py
  products/views.py
  users/tests.py
Labels: Status: 리뷰 요청

#31 [24기 성우진] ProductListView 수정
  products/views.py
Labels: Status: 리뷰 요청
